### ISSUE TITLE
Add Angular-Material to Chapitre3

### ISSUE THREAD

**Issue by benmed00** [PacktPublishing/Angular-Projects-Third-Edition#2]
Errors occurs when serving the project.
solution :
`ng add @angular/materia`

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
just take the package.json of the Chapitre3 put it on your project and do npm install

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
and firstly it's ng add @angular/material and not ng add @angular/materia
