### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dxxvi** [PacktPublishing/Angular-Projects-Third-Edition#3]
- As chapter 1 talks about routing, I think every chapter can be in 1 route. It'll be easier for readers to look at the code of previous chapters. Finally we'll have 1 giant app that doesn't make any sense, but who cares :) 
- Could you add some logging library in 1 of the examples? I'd like to log messages at different logging levels, set a logging level for a particular .ts file, set the logging level for the entire app to, for example, INFO when the app is built.

**Comment by bampakoa** [comment]
Thank you so much for your suggestions @dxxvi 🙏
