### ISSUE TITLE
CSS fix

### ISSUE THREAD

**Issue by iamhrk** [PacktPublishing/Angular-Projects-Third-Edition#4]
We need to add 2 more styles to the angular.json
and add the `cds-theme="light"` (or `cds-theme="dark"` for dark theme) to the body tag:
(This is mentioned in the @clr/ui/Readme.md)

            "styles": [
              "node_modules/@clr/ui/clr-ui.min.css",
              "node_modules/@cds/core/global.min.css",
              "node_modules/@cds/core/styles/theme.dark.min.css",
              "src/styles.css"
            ],
If we don't add the cds-them on body tag, the css won't apply.

**Comment by bampakoa** [comment]
Thank you for noticing that @iamhrk 🙏
