### ISSUE TITLE
Error in the chapter 4 of the book

### ISSUE THREAD

**Issue by iamhrk** [PacktPublishing/Angular-Projects-Third-Edition#5]
In chapter 3 of the book for making PWA weather application, it tells you to add the following scripts property to package.json

`"server": "http-server -p 8080 -c-1 dist/weather-app"`

But according to the angular docs [https://angular.io/guide/service-worker-getting-started#service-worker-in-action-a-tour](https://angular.io/guide/service-worker-getting-started#service-worker-in-action-a-tour), we should also add the **_browser_** to the end of the command. Otherwise a blank page will be shown.

**Correct way to run server is** 

`"server": "http-server -p 8080 -c-1 dist/weather-app/browser`

**Comment by bampakoa** [comment]
Hey @iamhrk 👋 The Angular documentation showcases how to work with service workers in Angular 17. Angular Projects Third Edition contains project that primarily work with Angular 16.
